---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: cert-manager
manifests:
  kustomize:
    paths:
    - hack/config/cert-manager
deploy:
  kubectl:
    defaultNamespace: ""
    flags:
      apply:
      - --server-side
      - --force-conflicts
---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: cert-manager-resources
manifests:
  kustomize:
    paths:
    - hack/config/cert-manager/resources
deploy:
  kubectl:
    defaultNamespace: ""
    flags:
      apply:
      - --server-side
      - --force-conflicts
---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: ingress-nginx
manifests:
  kustomize:
    paths:
    - hack/config/ingress-nginx/default
deploy:
  kubectl:
    hooks:
      before:
      - host:
          command:
          - /usr/bin/env
          - bash
          - -c
          # job template is immutable, delete the old job to prepare for upgrade
          - kubectl -n ingress-nginx delete job --ignore-not-found ingress-nginx-admission-create ingress-nginx-admission-patch
    defaultNamespace: ""
    flags:
      apply:
      - --server-side
      - --force-conflicts
profiles:
- name: kind
  activation:
  - kubeContext: kind-.*
  manifests:
    kustomize:
      paths:
      - hack/config/ingress-nginx/kind
- name: shoot
  activation:
  - kubeContext: .*--sharding.*
  manifests:
    kustomize:
      paths:
      - hack/config/ingress-nginx/shoot
---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: kyverno
manifests:
  kustomize:
    paths:
    - hack/config/kyverno
deploy:
  kubectl:
    defaultNamespace: ""
    flags:
      apply:
      - --server-side
      - --force-conflicts
---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: monitoring-crds
manifests:
  kustomize:
    paths:
    - hack/config/monitoring/crds
deploy:
  kubectl:
    defaultNamespace: ""
    flags:
      apply:
      - --server-side
      - --force-conflicts
---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: monitoring
requires:
- configs:
  - monitoring-crds
manifests:
  kustomize:
    paths:
    - hack/config/monitoring/default
  hooks:
    before:
    - host:
        command:
        - hack/config/monitoring/default/ensure-admin-password.sh
deploy:
  kubectl:
    defaultNamespace: ""
    flags:
      apply:
      - --server-side
      - --force-conflicts
profiles:
- name: shoot
  activation:
  - kubeContext: .*--sharding.*
  manifests:
    kustomize:
      paths:
      - hack/config/monitoring/shoot
portForward:
- resourceType: service
  namespace: monitoring
  resourceName: grafana
  port: http
  localPort: 3000
- resourceType: service
  namespace: monitoring
  resourceName: prometheus-k8s
  port: web
  localPort: 9090
---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: profiling
manifests:
  kustomize:
    paths:
    - hack/config/profiling
  hooks:
    before:
    - host:
        command:
        - hack/config/profiling/ensure-admin-password.sh
deploy:
  kubectl:
    defaultNamespace: ""
    flags:
      apply:
      - --server-side
      - --force-conflicts
portForward:
- resourceType: service
  namespace: parca
  resourceName: parca
  port: http
  localPort: 7070
