apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhosting-tls
spec:
  dnsNames:
  - webhosting.timebertt.dev
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-http01
  secretName: webhosting-tls
  usages:
  - digital signature
  - key encipherment
