apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhosting-exporter
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webhosting.timebertt.dev
  resources:
  - websites
  - themes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
