kind: CustomResourceStateMetrics
spec:
  resources:
  # website metrics
  - metricNamePrefix: kube_website
    groupVersionKind:
      group: webhosting.timebertt.dev
      version: v1alpha1
      kind: Website
    labelsFromPath:
      namespace: [metadata, namespace]
      website: [metadata, name]
      uid: [metadata, uid]
    metrics:
    - name: info
      help: "Information about a Website"
      each:
        type: Info
        info:
          labelsFromPath:
            theme: [spec, theme]
    - name: shard
      help: "Sharding information about a Website"
      each:
        type: Info
        info:
          labelsFromPath:
            shard: [metadata, labels, sharding.alpha.kubernetes.io/shard]
            drain: [metadata, labels, sharding.alpha.kubernetes.io/drain]
    - name: metadata_generation
      help: "The generation of a Website"
      each:
        type: Gauge
        gauge:
          path: [metadata, generation]
    - name: observed_generation
      help: "The latest generation observed by the Website controller"
      each:
        type: Gauge
        gauge:
          path: [status, observedGeneration]
    - name: status_phase
      help: "The Website's current phase"
      each:
        type: StateSet
        stateSet:
          labelName: phase
          path: [status, phase]
          list: [Pending, Ready, Error]
  # theme metrics
  - metricNamePrefix: kube_theme
    groupVersionKind:
      group: webhosting.timebertt.dev
      version: v1alpha1
      kind: Theme
    labelsFromPath:
      theme: [metadata, name]
    metrics:
    - name: info
      help: "Information about a Theme"
      each:
        type: Info
        info:
          labelsFromPath:
            color: [spec, color]
            font_family: [spec, fontFamily]
    - name: metadata_generation
      help: "The generation of a Theme"
      each:
        type: Gauge
        gauge:
          path: [metadata, generation]
