apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

generatorOptions:
  disableNameSuffixHash: true

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: webhosting-exporter

resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- rbac-proxy_clusterrolebinding.yaml
- serviceaccount.yaml
- service.yaml
- deployment.yaml
- servicemonitor.yaml

images:
- name: exporter
  newName: ghcr.io/timebertt/kubernetes-controller-sharding/webhosting-exporter
  newTag: latest

configMapGenerator:
- files:
  - dashboard-webhosting.json
  name: grafana-dashboard-webhosting
  options:
    labels:
      grafana_dashboard: "true"
