apiVersion: v1
kind: Service
metadata:
  name: webhosting-exporter
spec:
  clusterIP: None
  ports:
  - name: https-main
    port: 8443
    targetPort: https-main
  - name: https-self
    port: 9443
    targetPort: https-self
