apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  name: sharding
  namespace: garden-timebertt
spec:
  addons:
    kubernetesDashboard:
      enabled: false
    nginxIngress:
      enabled: false
  cloudProfileName: gcp
  dns:
    providers:
    - secretName: google-clouddns-timebertt-dev
      type: google-clouddns
  extensions:
  - type: shoot-cert-service
    providerConfig:
      apiVersion: service.cert.extensions.gardener.cloud/v1alpha1
      issuers:
      - email: timebertt@gmail.com
        name: letsencrypt
        server: https://acme-v02.api.letsencrypt.org/directory
      - email: timebertt@gmail.com
        name: letsencrypt-staging
        server: https://acme-staging-v02.api.letsencrypt.org/directory
  hibernation:
    schedules:
    - start: '00 19 * * 1,2,3,4,5'
      end: '30 07 * * 1,2,3,4,5'
      location: Europe/Berlin
  kubernetes:
    allowPrivilegedContainers: true
    kubeAPIServer:
      enableBasicAuthentication: false
    kubeControllerManager:
      nodeCIDRMaskSize: 20
    kubeProxy:
      mode: IPTables
    version: "1.24"
    verticalPodAutoscaler:
      enabled: true
    enableStaticTokenKubeconfig: false
  maintenance:
    autoUpdate:
      kubernetesVersion: true
      machineImageVersion: true
    timeWindow:
      begin: 030000+0200
      end: 040000+0200
  networking:
    nodes: 10.250.0.0/16
    pods: 100.96.0.0/11
    services: 100.64.0.0/13
    type: calico
  provider:
    controlPlaneConfig:
      apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
      kind: ControlPlaneConfig
      zone: europe-west1-c
    infrastructureConfig:
      apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      networks:
        workers: 10.250.0.0/16
    type: gcp
    workers:
    # runs system and monitoring components
    - name: system
      cri:
        name: containerd
      machine:
        image:
          name: gardenlinux
        type: n1-standard-8
      maxSurge: 1
      maxUnavailable: 0
      maximum: 1
      minimum: 1
      systemComponents:
        allow: true
      volume:
        size: 50Gi
        type: pd-ssd
      zones:
      - europe-west1-c
    # runs webhosting-operator
    - name: operator
      cri:
        name: containerd
      machine:
        image:
          name: gardenlinux
        type: n1-standard-4
      maxSurge: 1
      maxUnavailable: 0
      maximum: 2
      minimum: 1
      systemComponents:
        allow: false
      labels:
        dedicated-for: webhosting-operator
      taints:
      - key: dedicated-for
        value: webhosting-operator
        effect: NoSchedule
      volume:
        size: 50Gi
        type: pd-ssd
      zones:
      - europe-west1-c
    # runs websites (pause containers in load test)
    - name: websites
      cri:
        name: containerd
      machine:
        image:
          name: gardenlinux
        type: n1-standard-8
      maxSurge: 1
      maxUnavailable: 0
      maximum: 5
      minimum: 0
      systemComponents:
        allow: false
      labels:
        dedicated-for: websites
      taints:
      - key: dedicated-for
        value: websites
        effect: NoSchedule
      volume:
        size: 50Gi
        type: pd-ssd
      zones:
      - europe-west1-c
      kubernetes:
        kubelet:
          maxPods: 4000
  purpose: development
  region: europe-west1
  secretBindingName: shoot-operator-gcp
