---
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: webhosting-operator
build:
  local:
    useBuildkit: true
  artifacts:
  - image: ghcr.io/timebertt/kubernetes-controller-sharding/webhosting-operator
    docker:
      dockerfile: Dockerfile
      target: webhosting-operator
deploy:
  kustomize:
    flags:
      apply:
      - "--server-side"
    paths:
    - config/debug
  kubectl:
    manifests:
    - config/samples/project_namespace.yaml
portForward:
- resourceType: deployment
  namespace: webhosting-operator-system
  resourceName: webhosting-operator-controller-manager
  port: metrics
  localPort: 8080
---
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: monitoring-crds
deploy:
  kustomize:
    flags:
      apply:
      - "--server-side"
    paths:
    - config/monitoring/crds
---
apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: monitoring
requires:
- configs:
  - monitoring-crds
build:
  local:
    useBuildkit: true
  artifacts:
  - image: ghcr.io/timebertt/kubernetes-controller-sharding/webhosting-exporter
    docker:
      dockerfile: Dockerfile
      target: webhosting-exporter
deploy:
  kustomize:
    flags:
      apply:
      - "--server-side"
    hooks:
      before:
      - host:
          command:
          - bash
          - -c
          - '[ -f config/monitoring/grafana_admin_pass.secret.txt ] || cat /dev/urandom | tr -dc "a-zA-Z0-9" | head -c 32 > config/monitoring/grafana_admin_pass.secret.txt'
    paths:
    - config/monitoring
portForward:
- resourceType: service
  namespace: monitoring
  resourceName: grafana
  port: http
  localPort: 3000
- resourceType: service
  namespace: monitoring
  resourceName: prometheus-k8s
  port: web
  localPort: 9090
