---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: policy
profiles:
- name: shoot
  activation:
  - kubeContext: .*--sharding.*
  manifests:
    kustomize:
      paths:
      - config/policy
  deploy:
    kubectl:
      defaultNamespace: ""
      flags:
        apply:
        - --server-side
        - --force-conflicts
    statusCheck: false
---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: webhosting-operator
build:
  local:
    concurrency: 0
  artifacts:
  - image: ghcr.io/timebertt/kubernetes-controller-sharding/webhosting-operator
    ko:
      main: ./cmd/webhosting-operator
      dependencies:
        paths:
        - go.mod
        - '**/*.go'
        - ../../../../sigs.k8s.io/controller-runtime/**/*.go
manifests:
  kustomize:
    paths:
    - config/manager/default
deploy:
  kubectl:
    defaultNamespace: ""
    flags:
      apply:
      - --server-side
      - --force-conflicts
    hooks:
      before:
      - host:
          command:
          # ensure CRDs and RBAC are up-to-date
          - make
          - manifests
profiles:
- name: debug
  activation:
  - command: debug
  patches:
  - op: replace
    path: /manifests/kustomize/paths/0
    value: config/manager/debug
- name: shard
  patches:
  - op: replace
    path: /manifests/kustomize/paths/0
    value: config/manager/shard
- name: shoot
  activation:
  - kubeContext: .*--sharding.*
  patches:
  - op: replace
    path: /manifests/kustomize/paths/0
    value: config/manager/shoot
- name: shoot-non-sharded
  patches:
  - op: replace
    path: /manifests/kustomize/paths/0
    value: config/manager/shoot-non-sharded
---
# This is an optional module that activates the external sharding implementation by deploying the ClusterRing object.
# Set the USE_CLUSTERRING env var to true to activate this module.
# We keep this optional for now until the external sharding implementation is fully implemented so that we don't break
# trying out the existing implementation.
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: clusterring
profiles:
- name: clusterring
  activation:
  - command: USE_CLUSTERRING=true
  manifests:
    kustomize:
      paths:
      - config/manager/clusterring
  deploy:
    kubectl:
      defaultNamespace: ""
      flags:
        apply:
        - --server-side
        - --force-conflicts
---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: experiment
profiles:
- name: expirement
  activation:
  - env: EXPERIMENT_SCENARIO=.+
  build:
    local:
      concurrency: 0
    artifacts:
    - image: ghcr.io/timebertt/kubernetes-controller-sharding/experiment
      ko:
        main: ./cmd/experiment
        dependencies:
          paths:
          - go.mod
          - '**/*.go'
          - ../../../../sigs.k8s.io/controller-runtime/**/*.go
  manifests:
    kustomize:
      paths:
      - config/experiment/{{ .EXPERIMENT_SCENARIO }}
  deploy:
    kubectl:
      hooks:
        before:
          - host:
              command:
              - /usr/bin/env
              - bash
              - -c
              - |
                active_pods="$(kubectl -n experiment get job experiment -ojsonpath='{.status.active}' 2>dev/null)"
                if [ "${active_pods:-0}" -gt 0 ] && [ -z "$EXPERIMENT_DELETE_FORCE" ] ; then
                  echo "Experiment is running currently, refusing to delete the job. Set EXPERIMENT_DELETE_FORCE to override."
                  exit 1
                fi
                kubectl -n experiment delete job experiment --ignore-not-found --wait=true
      defaultNamespace: ""
      flags:
        apply:
        - --server-side
        - --force-conflicts
---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: monitoring
manifests:
  kustomize:
    paths:
    - config/monitoring
deploy:
  kubectl:
    defaultNamespace: ""
    flags:
      apply:
      - --server-side
      - --force-conflicts
