apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: kyverno
profiles:
# deploy only on shoot
- name: shoot
  activation:
  - kubeContext: .*fb28d21f90-99b0e--sharding.*
  manifests:
    kustomize:
      paths:
      - config/kyverno
  deploy:
    kubectl:
      defaultNamespace: ""
      flags:
        apply:
        - --server-side
        - --force-conflicts
---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: policy
requires:
- configs:
  - kyverno
profiles:
# deploy only on shoot
- name: shoot
  activation:
  - kubeContext: .*fb28d21f90-99b0e--sharding.*
  manifests:
    kustomize:
      paths:
      - config/policy
  deploy:
    kubectl:
      defaultNamespace: ""
      flags:
        apply:
        - --server-side
        - --force-conflicts
    statusCheck: false
---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: webhosting-operator
build:
  local:
    concurrency: 0
  artifacts:
  - image: ghcr.io/timebertt/kubernetes-controller-sharding/webhosting-operator
    ko:
      main: ./cmd/webhosting-operator
      dependencies:
        paths:
        - go.mod
        - '**/*.go'
        - ../../../../sigs.k8s.io/controller-runtime/**/*.go
manifests:
  kustomize:
    paths:
    - config/manager/default
deploy:
  kubectl:
    defaultNamespace: ""
    flags:
      apply:
      - --server-side
      - --force-conflicts
    hooks:
      before:
      - host:
          command:
          # ensure CRDs and RBAC are up-to-date
          - make
          - manifests
profiles:
- name: debug
  activation:
  - command: debug
  patches:
  - op: replace
    path: /manifests/kustomize/paths/0
    value: config/manager/debug
- name: shard
  patches:
  - op: replace
    path: /manifests/kustomize/paths/0
    value: config/manager/shard
- name: shoot
  activation:
  - kubeContext: .*fb28d21f90-99b0e--sharding.*
  patches:
  - op: replace
    path: /manifests/kustomize/paths/0
    value: config/manager/shoot
- name: shoot-non-sharded
  patches:
  - op: replace
    path: /manifests/kustomize/paths/0
    value: config/manager/shoot-non-sharded
portForward:
- resourceType: deployment
  namespace: webhosting-system
  resourceName: webhosting-operator
  port: metrics
  localPort: 8081
---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: monitoring-crds
manifests:
  kustomize:
    paths:
    - config/monitoring/crds
deploy:
  kubectl:
    defaultNamespace: ""
    flags:
      apply:
      - --server-side
      - --force-conflicts
---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: monitoring
requires:
- configs:
  - monitoring-crds
manifests:
  kustomize:
    paths:
    - config/monitoring/default
  hooks:
    before:
    - host:
        command:
        - bash
        - -c
        - '[ -f config/monitoring/default/grafana_admin_pass.secret.txt ] || cat /dev/urandom | tr -dc "a-zA-Z0-9" | head -c 32 > config/monitoring/default/grafana_admin_pass.secret.txt'
deploy:
  kubectl:
    defaultNamespace: ""
    flags:
      apply:
      - --server-side
      - --force-conflicts
profiles:
- name: shoot
  activation:
  - kubeContext: .*fb28d21f90-99b0e--sharding.*
  manifests:
    kustomize:
      paths:
      - config/monitoring/with-pvc
portForward:
- resourceType: service
  namespace: monitoring
  resourceName: grafana
  port: http
  localPort: 3000
- resourceType: service
  namespace: monitoring
  resourceName: prometheus-k8s
  port: web
  localPort: 9090
---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: profiling
# profiling config disabled by default, can be enabled with profile "profiling"
profiles:
- name: profiling
  manifests:
    kustomize:
      paths:
      - config/profiling
  deploy:
    kubectl:
      defaultNamespace: ""
      flags:
        apply:
        - --server-side
        - --force-conflicts
  portForward:
  - resourceType: service
    namespace: parca
    resourceName: parca
    port: http
    localPort: 7070
