apiVersion: batch/v1
kind: CronJob
metadata:
  name: janitor
  namespace: parca
spec:
  concurrencyPolicy: Forbid
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/component: janitor
            app.kubernetes.io/instance: parca
            app.kubernetes.io/name: parca
        spec:
          restartPolicy: Never
          containers:
          - name: janitor
            image: janitor
            args:
            - /var/lib/parca/blocks/parca/stacktraces
            - --max-age=48h
            volumeMounts:
            - mountPath: /var/lib/parca
              name: parca
          securityContext:
            fsGroupChangePolicy: OnRootMismatch
            fsGroup: 65534
            runAsNonRoot: true
            runAsUser: 65534
            seccompProfile:
              type: RuntimeDefault
            supplementalGroups:
            - 65534
          volumes:
          - name: parca
            persistentVolumeClaim:
              claimName: parca
          # Require janitor to be scheduled to the same node as parca itself because the volume is RWO and cannot be
          # attached to multiple nodes simultaneously.
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/component: observability
                    app.kubernetes.io/instance: parca
                    app.kubernetes.io/name: parca
