apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../default

patches:
- target:
    group: apps
    version: v1
    kind: DaemonSet
    name: node-exporter
    namespace: monitoring
  patch: |
    - op: test
      path: "/spec/template/spec/containers/0/volumeMounts/0/name"
      value: "sys"
    - op: remove
      path: "/spec/template/spec/containers/0/volumeMounts/0/mountPropagation"
