# permissions for end users to edit themes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: theme-editor-role
rules:
- apiGroups:
  - webhosting.timebertt.dev
  resources:
  - themes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webhosting.timebertt.dev
  resources:
  - themes/status
  verbs:
  - get
