# permissions for end users to view themes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: theme-viewer-role
rules:
- apiGroups:
  - webhosting.timebertt.dev
  resources:
  - themes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webhosting.timebertt.dev
  resources:
  - themes/status
  verbs:
  - get
