apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/kyverno/kyverno//config?ref=v1.8.0

images:
- name: ghcr.io/kyverno/kyverno
  newTag: v1.8.0
- name: ghcr.io/kyverno/kyvernopre
  newTag: v1.8.0

configMapGenerator:
- name: kyverno
  namespace: kyverno
  behavior: merge
  options:
    disableNameSuffixHash: true
  literals:
  # overwrite default namespaceSelector for webhook configs to exclude kube-system
  # the second part makes gardeners care controller/webhook remediation happy
  - >-
    webhooks=[{
      "namespaceSelector": {
        "matchExpressions": [{
          "key": "kubernetes.io/metadata.name",
          "operator": "NotIn",
          "values": ["kyverno", "kube-system"]
        }, {
          "key": "gardener.cloud/purpose",
          "operator": "NotIn",
          "values": ["kube-system"]
        }]
      }
    }]
