---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sharding:sharder:leader-election
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sharding:sharder:leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sharding:sharder:leader-election
subjects:
- kind: ServiceAccount
  name: sharder
  namespace: sharding-system
