---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sharding:sharder:pprof-reader
rules:
- nonResourceURLs:
  - "/debug/pprof/allocs"
  - "/debug/pprof/block"
  - "/debug/pprof/goroutine"
  - "/debug/pprof/heap"
  - "/debug/pprof/mutex"
  - "/debug/pprof/profile"
  - "/debug/pprof/symbol"
  - "/debug/pprof/threadcreate"
  - "/debug/pprof/trace"
  verbs:
  - get
