---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sharder
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
