apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http01
spec:
  acme:
    email: null@timebertt.dev
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: http01-timebertt-dev
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
