apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# from https://github.com/parca-dev/parca/releases/download/v0.12.1/kubernetes-manifest.yaml
- parca.yaml
# provide parca running in namespace "parca" with the permissions required for service discovery in namespace
# "webhosting-system" and scrape the pprof endpoints of webhosting-operator
- parca_rbac.yaml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/component: observability
    app.kubernetes.io/instance: parca
    app.kubernetes.io/name: parca

configMapGenerator:
- name: parca-config
  namespace: parca
  behavior: merge
  files:
  - parca.yaml=parca_config.yaml
