apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../grafana-sidecar

resources:
- namespace.yaml
- rbac-proxy_clusterrole.yaml
- ../kube-prometheus
- grafana_ingress.yaml
- ../webhosting-exporter
- ../webhosting-operator

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: grafana-admin
  namespace: monitoring
  files:
  - password=grafana_admin_pass.secret.txt

patchesStrategicMerge:
- patch_grafana_admin.yaml

patches:
- path: patch_grafana_networkpolicy.yaml
  target:
    group: networking.k8s.io
    version: v1
    kind: NetworkPolicy
    name: grafana
    namespace: monitoring
