apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../grafana-sidecar

resources:
- namespace.yaml
- rbac-proxy_clusterrole.yaml
- ../kube-prometheus
- grafana_ingress.yaml
- ../webhosting-exporter
- ../webhosting-operator

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - dashboards/client-go.json
  - dashboards/controller-details.json
  - dashboards/controller-runtime.json
  - dashboards/sharding.json
  - dashboards/webhosting.json
  name: grafana-dashboard-webhosting
  namespace: monitoring
  options:
    labels:
      grafana_dashboard: "true"

secretGenerator:
- name: grafana-admin
  namespace: monitoring
  files:
  - password=grafana_admin_pass.secret.txt

patchesStrategicMerge:
- patch_grafana_admin.yaml
- patch_prometheus_resources.yaml

patches:
- path: patch_grafana_networkpolicy.yaml
  target:
    group: networking.k8s.io
    version: v1
    kind: NetworkPolicy
    name: grafana
    namespace: monitoring
- path: patch_filter_kubelet_metrics.yaml
  target:
    group: monitoring.coreos.com
    version: v1
    kind: ServiceMonitor
    name: kubelet
    namespace: monitoring
- path: patch_filter_kubestatemetrics_metrics.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: kube-state-metrics
    namespace: monitoring
- path: patch_filter_nodeexporter_metrics.yaml
  target:
    group: monitoring.coreos.com
    version: v1
    kind: ServiceMonitor
    name: node-exporter
    namespace: monitoring
