apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  namespace: monitoring
spec:
  replicas: 1 # don't need HA for our purposes
  resources:
    requests:
      cpu: 100m
      memory: 1Gi
    limits:
      cpu: "1" # replaying WAL takes some CPU
      memory: 2Gi
