apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  namespace: monitoring
spec:
  replicas: 1 # don't need HA for our purposes
  alerting: null
  resources:
    requests:
      cpu: 500m
      memory: 6Gi
    limits:
      cpu: 1500m # replaying WAL takes some CPU
      memory: 8Gi
