apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: experiment-scheduling
spec:
  failurePolicy: Fail
  rules:
  # schedule experiment on dedicated worker pool for better isolation in load tests
  - name: add-scheduling-constraints
    match:
      any:
      - resources:
          kinds:
          - Pod
          namespaces:
          - experiment
          selector:
            matchLabels:
              app.kubernetes.io/name: experiment
          operations:
          - CREATE
    mutate:
      patchesJson6902: |-
        - op: add
          path: "/spec/tolerations/-"
          value: {"key":"dedicated-for","operator":"Equal","value":"experiment","effect":"NoSchedule"}        
        - op: add
          path: "/spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution/nodeSelectorTerms/-"
          value: {"matchExpressions": [{"key":"dedicated-for","operator":"In","values":["experiment"]}]}        
