apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../default
- prepull-nginx.yaml
- webhosting-operator-scheduling.yaml
- websites-scheduling.yaml

images:
- name: pause
  newName: registry.k8s.io/pause
  newTag: "3.7"
