apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: webhosting-operator
  namespace: webhosting-operator-system
spec:
  endpoints:
  - path: /metrics
    port: https
    scheme: https
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    tlsConfig:
      insecureSkipVerify: true
    relabelings:
    - targetLabel: job
      replacement: webhosting-operator
  selector:
    matchLabels:
      app.kubernetes.io/name: webhosting-operator
