apiVersion: config.webhosting.timebertt.dev/v1alpha1
kind: WebhostingOperatorConfig
health:
  healthProbeBindAddress: :8081
metrics:
  bindAddress: 127.0.0.1:8080
webhook:
  port: 9443
gracefulShutDown: 15s
leaderElection:
  leaderElect: true
  resourceLock: leases
  resourceName: webhosting-operator
  resourceNamespace: webhosting-system
debugging:
  enableProfiling: true
  enableContentionProfiling: true
clientConnection:
  qps: 800
  burst: 1000
ingress:
  hosts:
  - webhosting.timebertt.dev
  tls:
  - hosts:
    - webhosting.timebertt.dev
