apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx

resources:
- https://github.com/kubernetes/ingress-nginx//deploy/static/provider/cloud?ref=controller-v1.8.1

patches:
- path: patch_default_ingress_class.yaml
- path: patch_controller_resources.yaml
# Delete validation webhook for Ingresses.
# We don't need or want validation for Ingress objects in the development and load testing setup. It results in high
# latency for API requests and CPU waste during load tests.
- patch: |
    apiVersion: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    metadata:
      name: ingress-nginx-admission
    $patch: delete
