apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../default

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
  behavior: replace
