apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app.kubernetes.io/component: sharder
  name: sharder
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: sharder
