apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/parca-dev/parca/releases/download/v0.18.0/kubernetes-manifest.yaml
# provide parca running in namespace "parca" with the permissions required for service discovery in namespace
# "webhosting-system" and scrape the pprof endpoints of webhosting-operator
- parca_rbac.yaml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/component: observability
    app.kubernetes.io/instance: parca
    app.kubernetes.io/name: parca

configMapGenerator:
- name: parca
  namespace: parca
  behavior: merge
  files:
  - parca.yaml=parca_config.yaml

patches:
- patch: |
    apiVersion: policy/v1beta1
    kind: PodSecurityPolicy
    metadata:
      name: parca
    $patch: delete
