apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/parca-dev/parca/releases/download/v0.20.0/kubernetes-manifest.yaml
# provide parca running in namespace "parca" with the permissions required for service discovery in namespace
# "webhosting-system" and scrape the pprof endpoints of webhosting-operator
- parca_rbac.yaml
- parca_ingress.yaml
- parca-pvc.yaml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/component: observability
    app.kubernetes.io/instance: parca
    app.kubernetes.io/name: parca

configMapGenerator:
- name: parca
  namespace: parca
  behavior: merge
  files:
  - parca.yaml=parca_config.yaml

secretGenerator:
- name: parca-basic-auth
  namespace: parca
  literals:
  - username=parca
  files:
  - password=parca_password.secret.txt
  - auth=parca_auth.secret.txt

patches:
- path: patch-deployment-pvc.yaml
- target:
    kind: Deployment
    name: parca
    namespace: parca
  patch: |
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --enable-persistence
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --storage-path=/var/lib/parca
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --storage-enable-wal
