---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: observability
    app.kubernetes.io/instance: parca
    app.kubernetes.io/name: parca
  name: parca-service-discovery
  namespace: webhosting-system
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: observability
    app.kubernetes.io/instance: parca
    app.kubernetes.io/name: parca
  name: parca-service-discovery
  namespace: webhosting-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: parca-service-discovery
subjects:
- kind: ServiceAccount
  name: parca
  namespace: parca
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: observability
    app.kubernetes.io/instance: parca
    app.kubernetes.io/name: parca
  name: parca-pprof-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webhosting-operator-pprof-reader
subjects:
- kind: ServiceAccount
  name: parca
  namespace: parca
