apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../default

patches:
- path: patch_service.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: ingress-nginx-controller
    namespace: ingress-nginx
  patch: |
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: "--default-ssl-certificate=ingress-nginx/webhosting-tls"
