apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- grafana-sidecar

resources:
- namespace.yaml
- rbac-proxy_clusterrole.yaml
- kube-prometheus
- grafana_ingress.yaml
- webhosting-exporter
- webhosting-operator_servicemonitor.yaml
# provide prometheus running in namespace "monitoring" with the permissions required for service discovery in namespace
# "webhosting-operator-system"
- webhosting-operator_prometheus_rbac.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: grafana-admin
  namespace: monitoring
  files:
  - password=grafana_admin_pass.secret.txt

patchesStrategicMerge:
- patch_grafana_admin.yaml
