apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- kube-prometheus
- grafana_ingress.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: grafana-admin
  namespace: monitoring
  files:
  - password=grafana_admin_pass.secret.txt

patchesStrategicMerge:
- patch_grafana_admin.yaml
