apiVersion: config.webhosting.timebertt.dev/v1alpha1
kind: ControllerManagerConfig
health:
  healthProbeBindAddress: :8081
metrics:
  bindAddress: 127.0.0.1:8080
webhook:
  port: 9443
gracefulShutDown: 15s
leaderElection:
  # disable leader election for debugging and use Deployment strategy Recreate.
  # other option would have been to increase the durations and rely on ReleaseOnCancel to release the lease,
  # however the delve debugger seems to kill the child process too fast for the leader elector to release the lease
  # (probably, this is because the network connection to the skaffold/dlv client breaks off during termination)
  leaderElect: false

