apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: false
      containers:
      - name: manager
        args:
        - "--metrics-bind-address=:8080"
        ports:
        - name: metrics
          containerPort: 8080
          protocol: TCP
