apiVersion: apps/v1
kind: Deployment
metadata:
  name: shard
spec:
  replicas: 3
  template:
    spec:
      automountServiceAccountToken: true
      securityContext:
        runAsNonRoot: true
      containers:
      - name: shard
        image: shard:latest
        args:
        - --clusterring=example
        - --shard=$(POD_NAME)
        - --zap-log-level=debug
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DISABLE_HTTP2
          value: "true"
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          requests:
            cpu: 25m
            memory: 50Mi
      serviceAccountName: shard
      terminationGracePeriodSeconds: 10
