apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: system
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: SHARDING_ENABLED
          value: "false"
